// Typed sensor upload contract (B1CF-2107).
//
// This file is the source of truth. Enigma-Subscriber, Enigma-Data-Generator and Enigma-Sensor
// each keep a byte-identical copy, and their CI fails if it drifts from this one. Change it here
// first, then copy it to the other repos.
//
// It is deliberately separate from grpc_config.proto: the copies of that file already differ
// between repos, so it cannot be checked for drift. The legacy uploadExcelMethod stays there.
//
// Code generation needs protoc 3.15 or newer: older versions reject `optional` in proto3.
//
// Compatibility rules:
// - Adding an optional field to an existing record is backward compatible. An old reader skips
//   the unknown field, so the column is simply missing until the Subscriber learns it.
// - Adding a log type is NOT free. An old Subscriber skips the new repeated field and drops those
//   records silently, and an upload carrying only the new type counts as 0 records, which the
//   Publisher refuses. Deploy in this order: the Subscriber decodes it, then the Publisher adds
//   the count key (RECORD_COUNT_KEYS), then senders start sending it.
// - Renaming, retyping or removing a field is not compatible. Add the new schema version to the
//   Subscriber, then to SUPPORTED_SCHEMA_VERSIONS in the Publisher, before any sender uses it.
// - Never reuse a field number. When a field is removed, add its number and name to `reserved`
//   in its message so neither can be reused by accident.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: sensor_records.proto

package ingest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorIngest_UploadRecords_FullMethodName = "/enigma.ingest.v1.SensorIngest/uploadRecords"
)

// SensorIngestClient is the client API for SensorIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorIngestClient interface {
	UploadRecords(ctx context.Context, in *UploadRecordsRequest, opts ...grpc.CallOption) (*UploadRecordsResponse, error)
}

type sensorIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorIngestClient(cc grpc.ClientConnInterface) SensorIngestClient {
	return &sensorIngestClient{cc}
}

func (c *sensorIngestClient) UploadRecords(ctx context.Context, in *UploadRecordsRequest, opts ...grpc.CallOption) (*UploadRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadRecordsResponse)
	err := c.cc.Invoke(ctx, SensorIngest_UploadRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorIngestServer is the server API for SensorIngest service.
// All implementations must embed UnimplementedSensorIngestServer
// for forward compatibility.
type SensorIngestServer interface {
	UploadRecords(context.Context, *UploadRecordsRequest) (*UploadRecordsResponse, error)
	mustEmbedUnimplementedSensorIngestServer()
}

// UnimplementedSensorIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorIngestServer struct{}

func (UnimplementedSensorIngestServer) UploadRecords(context.Context, *UploadRecordsRequest) (*UploadRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadRecords not implemented")
}
func (UnimplementedSensorIngestServer) mustEmbedUnimplementedSensorIngestServer() {}
func (UnimplementedSensorIngestServer) testEmbeddedByValue()                      {}

// UnsafeSensorIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorIngestServer will
// result in compilation errors.
type UnsafeSensorIngestServer interface {
	mustEmbedUnimplementedSensorIngestServer()
}

func RegisterSensorIngestServer(s grpc.ServiceRegistrar, srv SensorIngestServer) {
	// If the following call pancis, it indicates UnimplementedSensorIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorIngest_ServiceDesc, srv)
}

func _SensorIngest_UploadRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorIngestServer).UploadRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorIngest_UploadRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorIngestServer).UploadRecords(ctx, req.(*UploadRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorIngest_ServiceDesc is the grpc.ServiceDesc for SensorIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enigma.ingest.v1.SensorIngest",
	HandlerType: (*SensorIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "uploadRecords",
			Handler:    _SensorIngest_UploadRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sensor_records.proto",
}
