// Typed sensor upload contract (B1CF-2107).
//
// This file is the source of truth. Enigma-Subscriber, Enigma-Data-Generator and Enigma-Sensor
// each keep a byte-identical copy, and their CI fails if it drifts from this one. Change it here
// first, then copy it to the other repos.
//
// It is deliberately separate from grpc_config.proto: the copies of that file already differ
// between repos, so it cannot be checked for drift. The legacy uploadExcelMethod stays there.
//
// Code generation needs protoc 3.15 or newer: older versions reject `optional` in proto3.
//
// Compatibility rules:
// - Adding an optional field to an existing record is backward compatible. An old reader skips
//   the unknown field, so the column is simply missing until the Subscriber learns it.
// - Adding a log type is NOT free. An old Subscriber skips the new repeated field and drops those
//   records silently, and an upload carrying only the new type counts as 0 records, which the
//   Publisher refuses. Deploy in this order: the Subscriber decodes it, then the Publisher adds
//   the count key (RECORD_COUNT_KEYS), then senders start sending it.
// - Renaming, retyping or removing a field is not compatible. Add the new schema version to the
//   Subscriber, then to SUPPORTED_SCHEMA_VERSIONS in the Publisher, before any sender uses it.
// - Never reuse a field number. When a field is removed, add its number and name to `reserved`
//   in its message so neither can be reused by accident.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: sensor_records.proto

package ingest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compression int32

const (
	// Refused. Senders must set compression explicitly.
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	// zlib (RFC 1950), the format the sensor already uses for uploadExcelMethod.
	Compression_COMPRESSION_ZLIB Compression = 1
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_ZLIB",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_ZLIB":        1,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_sensor_records_proto_enumTypes[0].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_sensor_records_proto_enumTypes[0]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{0}
}

type UploadRecordsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ApiKey string                 `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	// Version of the RecordBatch layout inside `records`. The Publisher refuses versions it does
	// not know.
	SchemaVersion uint32        `protobuf:"varint,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	SensorVersion string        `protobuf:"bytes,3,opt,name=sensorVersion,proto3" json:"sensorVersion,omitempty"`
	Counts        *RecordCounts `protobuf:"bytes,4,opt,name=counts,proto3" json:"counts,omitempty"`
	Compression   Compression   `protobuf:"varint,5,opt,name=compression,proto3,enum=enigma.ingest.v1.Compression" json:"compression,omitempty"`
	// The same string map uploadExcelMethod carries: network_id, machine_id, os_name, os_version,
	// architecture, host_ips, zeek_version, session_id.
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A RecordBatch, serialized and then compressed with `compression`. Kept as bytes so the
	// Publisher never decodes it.
	Records       []byte `protobuf:"bytes,7,opt,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRecordsRequest) Reset() {
	*x = UploadRecordsRequest{}
	mi := &file_sensor_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRecordsRequest) ProtoMessage() {}

func (x *UploadRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRecordsRequest.ProtoReflect.Descriptor instead.
func (*UploadRecordsRequest) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRecordsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UploadRecordsRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *UploadRecordsRequest) GetSensorVersion() string {
	if x != nil {
		return x.SensorVersion
	}
	return ""
}

func (x *UploadRecordsRequest) GetCounts() *RecordCounts {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *UploadRecordsRequest) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *UploadRecordsRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UploadRecordsRequest) GetRecords() []byte {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          uint32                 `protobuf:"varint,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Dns           uint32                 `protobuf:"varint,2,opt,name=dns,proto3" json:"dns,omitempty"`
	Dhcp          uint32                 `protobuf:"varint,3,opt,name=dhcp,proto3" json:"dhcp,omitempty"`
	Ja3Ja4        uint32                 `protobuf:"varint,4,opt,name=ja3Ja4,proto3" json:"ja3Ja4,omitempty"`
	Ja4S          uint32                 `protobuf:"varint,5,opt,name=ja4s,proto3" json:"ja4s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordCounts) Reset() {
	*x = RecordCounts{}
	mi := &file_sensor_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCounts) ProtoMessage() {}

func (x *RecordCounts) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCounts.ProtoReflect.Descriptor instead.
func (*RecordCounts) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{1}
}

func (x *RecordCounts) GetConn() uint32 {
	if x != nil {
		return x.Conn
	}
	return 0
}

func (x *RecordCounts) GetDns() uint32 {
	if x != nil {
		return x.Dns
	}
	return 0
}

func (x *RecordCounts) GetDhcp() uint32 {
	if x != nil {
		return x.Dhcp
	}
	return 0
}

func (x *RecordCounts) GetJa3Ja4() uint32 {
	if x != nil {
		return x.Ja3Ja4
	}
	return 0
}

func (x *RecordCounts) GetJa4S() uint32 {
	if x != nil {
		return x.Ja4S
	}
	return 0
}

// Same shape as uploadExcelResponse: the outcome is in statusCode and the RPC itself succeeds.
type UploadRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRecordsResponse) Reset() {
	*x = UploadRecordsResponse{}
	mi := &file_sensor_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRecordsResponse) ProtoMessage() {}

func (x *UploadRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRecordsResponse.ProtoReflect.Descriptor instead.
func (*UploadRecordsResponse) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRecordsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadRecordsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UploadRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RecordBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conn          []*ConnRecord          `protobuf:"bytes,1,rep,name=conn,proto3" json:"conn,omitempty"`
	Dns           []*DnsRecord           `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	Dhcp          []*DhcpRecord          `protobuf:"bytes,3,rep,name=dhcp,proto3" json:"dhcp,omitempty"`
	Ja3Ja4        []*Ja3Ja4Record        `protobuf:"bytes,4,rep,name=ja3Ja4,proto3" json:"ja3Ja4,omitempty"`
	Ja4S          []*Ja4SRecord          `protobuf:"bytes,5,rep,name=ja4s,proto3" json:"ja4s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordBatch) Reset() {
	*x = RecordBatch{}
	mi := &file_sensor_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBatch) ProtoMessage() {}

func (x *RecordBatch) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBatch.ProtoReflect.Descriptor instead.
func (*RecordBatch) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{3}
}

func (x *RecordBatch) GetConn() []*ConnRecord {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *RecordBatch) GetDns() []*DnsRecord {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *RecordBatch) GetDhcp() []*DhcpRecord {
	if x != nil {
		return x.Dhcp
	}
	return nil
}

func (x *RecordBatch) GetJa3Ja4() []*Ja3Ja4Record {
	if x != nil {
		return x.Ja3Ja4
	}
	return nil
}

func (x *RecordBatch) GetJa4S() []*Ja4SRecord {
	if x != nil {
		return x.Ja4S
	}
	return nil
}

type ConnRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            float64                `protobuf:"fixed64,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	OrigH         string                 `protobuf:"bytes,3,opt,name=orig_h,json=origH,proto3" json:"orig_h,omitempty"`
	OrigP         uint32                 `protobuf:"varint,4,opt,name=orig_p,json=origP,proto3" json:"orig_p,omitempty"`
	RespH         string                 `protobuf:"bytes,5,opt,name=resp_h,json=respH,proto3" json:"resp_h,omitempty"`
	RespP         uint32                 `protobuf:"varint,6,opt,name=resp_p,json=respP,proto3" json:"resp_p,omitempty"`
	Proto         string                 `protobuf:"bytes,7,opt,name=proto,proto3" json:"proto,omitempty"`
	Service       *string                `protobuf:"bytes,8,opt,name=service,proto3,oneof" json:"service,omitempty"`
	Duration      *float64               `protobuf:"fixed64,9,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	OrigBytes     *uint64                `protobuf:"varint,10,opt,name=orig_bytes,json=origBytes,proto3,oneof" json:"orig_bytes,omitempty"`
	RespBytes     *uint64                `protobuf:"varint,11,opt,name=resp_bytes,json=respBytes,proto3,oneof" json:"resp_bytes,omitempty"`
	ConnState     *string                `protobuf:"bytes,12,opt,name=conn_state,json=connState,proto3,oneof" json:"conn_state,omitempty"`
	LocalOrig     *bool                  `protobuf:"varint,13,opt,name=local_orig,json=localOrig,proto3,oneof" json:"local_orig,omitempty"`
	LocalResp     *bool                  `protobuf:"varint,14,opt,name=local_resp,json=localResp,proto3,oneof" json:"local_resp,omitempty"`
	MissedBytes   *uint64                `protobuf:"varint,15,opt,name=missed_bytes,json=missedBytes,proto3,oneof" json:"missed_bytes,omitempty"`
	History       *string                `protobuf:"bytes,16,opt,name=history,proto3,oneof" json:"history,omitempty"`
	OrigPkts      *uint64                `protobuf:"varint,17,opt,name=orig_pkts,json=origPkts,proto3,oneof" json:"orig_pkts,omitempty"`
	OrigIpBytes   *uint64                `protobuf:"varint,18,opt,name=orig_ip_bytes,json=origIpBytes,proto3,oneof" json:"orig_ip_bytes,omitempty"`
	RespPkts      *uint64                `protobuf:"varint,19,opt,name=resp_pkts,json=respPkts,proto3,oneof" json:"resp_pkts,omitempty"`
	RespIpBytes   *uint64                `protobuf:"varint,20,opt,name=resp_ip_bytes,json=respIpBytes,proto3,oneof" json:"resp_ip_bytes,omitempty"`
	TunnelParents *string                `protobuf:"bytes,21,opt,name=tunnel_parents,json=tunnelParents,proto3,oneof" json:"tunnel_parents,omitempty"`
	// IP protocol number, added to conn.log in Zeek 7. Kept separate on purpose: the Subscriber's
	// tab-separated parser renames ip_proto to proto, so on that path it overwrites the transport
	// name ("tcp") with the number (6). The typed decoder has to choose which behaviour to match.
	IpProto       *uint32 `protobuf:"varint,22,opt,name=ip_proto,json=ipProto,proto3,oneof" json:"ip_proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnRecord) Reset() {
	*x = ConnRecord{}
	mi := &file_sensor_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnRecord) ProtoMessage() {}

func (x *ConnRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnRecord.ProtoReflect.Descriptor instead.
func (*ConnRecord) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{4}
}

func (x *ConnRecord) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ConnRecord) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ConnRecord) GetOrigH() string {
	if x != nil {
		return x.OrigH
	}
	return ""
}

func (x *ConnRecord) GetOrigP() uint32 {
	if x != nil {
		return x.OrigP
	}
	return 0
}

func (x *ConnRecord) GetRespH() string {
	if x != nil {
		return x.RespH
	}
	return ""
}

func (x *ConnRecord) GetRespP() uint32 {
	if x != nil {
		return x.RespP
	}
	return 0
}

func (x *ConnRecord) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *ConnRecord) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *ConnRecord) GetDuration() float64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *ConnRecord) GetOrigBytes() uint64 {
	if x != nil && x.OrigBytes != nil {
		return *x.OrigBytes
	}
	return 0
}

func (x *ConnRecord) GetRespBytes() uint64 {
	if x != nil && x.RespBytes != nil {
		return *x.RespBytes
	}
	return 0
}

func (x *ConnRecord) GetConnState() string {
	if x != nil && x.ConnState != nil {
		return *x.ConnState
	}
	return ""
}

func (x *ConnRecord) GetLocalOrig() bool {
	if x != nil && x.LocalOrig != nil {
		return *x.LocalOrig
	}
	return false
}

func (x *ConnRecord) GetLocalResp() bool {
	if x != nil && x.LocalResp != nil {
		return *x.LocalResp
	}
	return false
}

func (x *ConnRecord) GetMissedBytes() uint64 {
	if x != nil && x.MissedBytes != nil {
		return *x.MissedBytes
	}
	return 0
}

func (x *ConnRecord) GetHistory() string {
	if x != nil && x.History != nil {
		return *x.History
	}
	return ""
}

func (x *ConnRecord) GetOrigPkts() uint64 {
	if x != nil && x.OrigPkts != nil {
		return *x.OrigPkts
	}
	return 0
}

func (x *ConnRecord) GetOrigIpBytes() uint64 {
	if x != nil && x.OrigIpBytes != nil {
		return *x.OrigIpBytes
	}
	return 0
}

func (x *ConnRecord) GetRespPkts() uint64 {
	if x != nil && x.RespPkts != nil {
		return *x.RespPkts
	}
	return 0
}

func (x *ConnRecord) GetRespIpBytes() uint64 {
	if x != nil && x.RespIpBytes != nil {
		return *x.RespIpBytes
	}
	return 0
}

func (x *ConnRecord) GetTunnelParents() string {
	if x != nil && x.TunnelParents != nil {
		return *x.TunnelParents
	}
	return ""
}

func (x *ConnRecord) GetIpProto() uint32 {
	if x != nil && x.IpProto != nil {
		return *x.IpProto
	}
	return 0
}

type DnsRecord struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Ts         float64                `protobuf:"fixed64,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Uid        string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	OrigH      string                 `protobuf:"bytes,3,opt,name=orig_h,json=origH,proto3" json:"orig_h,omitempty"`
	OrigP      uint32                 `protobuf:"varint,4,opt,name=orig_p,json=origP,proto3" json:"orig_p,omitempty"`
	RespH      string                 `protobuf:"bytes,5,opt,name=resp_h,json=respH,proto3" json:"resp_h,omitempty"`
	RespP      uint32                 `protobuf:"varint,6,opt,name=resp_p,json=respP,proto3" json:"resp_p,omitempty"`
	Proto      string                 `protobuf:"bytes,7,opt,name=proto,proto3" json:"proto,omitempty"`
	TransId    *uint32                `protobuf:"varint,8,opt,name=trans_id,json=transId,proto3,oneof" json:"trans_id,omitempty"`
	Rtt        *float64               `protobuf:"fixed64,9,opt,name=rtt,proto3,oneof" json:"rtt,omitempty"`
	Query      *string                `protobuf:"bytes,10,opt,name=query,proto3,oneof" json:"query,omitempty"`
	Qclass     *uint32                `protobuf:"varint,11,opt,name=qclass,proto3,oneof" json:"qclass,omitempty"`
	QclassName *string                `protobuf:"bytes,12,opt,name=qclass_name,json=qclassName,proto3,oneof" json:"qclass_name,omitempty"`
	Qtype      *uint32                `protobuf:"varint,13,opt,name=qtype,proto3,oneof" json:"qtype,omitempty"`
	QtypeName  *string                `protobuf:"bytes,14,opt,name=qtype_name,json=qtypeName,proto3,oneof" json:"qtype_name,omitempty"`
	Rcode      *uint32                `protobuf:"varint,15,opt,name=rcode,proto3,oneof" json:"rcode,omitempty"`
	RcodeName  *string                `protobuf:"bytes,16,opt,name=rcode_name,json=rcodeName,proto3,oneof" json:"rcode_name,omitempty"`
	AA         *bool                  `protobuf:"varint,17,opt,name=AA,proto3,oneof" json:"AA,omitempty"`
	TC         *bool                  `protobuf:"varint,18,opt,name=TC,proto3,oneof" json:"TC,omitempty"`
	RD         *bool                  `protobuf:"varint,19,opt,name=RD,proto3,oneof" json:"RD,omitempty"`
	RA         *bool                  `protobuf:"varint,20,opt,name=RA,proto3,oneof" json:"RA,omitempty"`
	Z          *uint32                `protobuf:"varint,21,opt,name=Z,proto3,oneof" json:"Z,omitempty"`
	Answers    *string                `protobuf:"bytes,22,opt,name=answers,proto3,oneof" json:"answers,omitempty"`
	TTLs       *string                `protobuf:"bytes,23,opt,name=TTLs,proto3,oneof" json:"TTLs,omitempty"`
	Rejected   *bool                  `protobuf:"varint,24,opt,name=rejected,proto3,oneof" json:"rejected,omitempty"`
	// Added to dns.log in Zeek 8.1 (B1CF-1902).
	Opcode        *uint32 `protobuf:"varint,25,opt,name=opcode,proto3,oneof" json:"opcode,omitempty"`
	OpcodeName    *string `protobuf:"bytes,26,opt,name=opcode_name,json=opcodeName,proto3,oneof" json:"opcode_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsRecord) Reset() {
	*x = DnsRecord{}
	mi := &file_sensor_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsRecord) ProtoMessage() {}

func (x *DnsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsRecord.ProtoReflect.Descriptor instead.
func (*DnsRecord) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{5}
}

func (x *DnsRecord) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *DnsRecord) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DnsRecord) GetOrigH() string {
	if x != nil {
		return x.OrigH
	}
	return ""
}

func (x *DnsRecord) GetOrigP() uint32 {
	if x != nil {
		return x.OrigP
	}
	return 0
}

func (x *DnsRecord) GetRespH() string {
	if x != nil {
		return x.RespH
	}
	return ""
}

func (x *DnsRecord) GetRespP() uint32 {
	if x != nil {
		return x.RespP
	}
	return 0
}

func (x *DnsRecord) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *DnsRecord) GetTransId() uint32 {
	if x != nil && x.TransId != nil {
		return *x.TransId
	}
	return 0
}

func (x *DnsRecord) GetRtt() float64 {
	if x != nil && x.Rtt != nil {
		return *x.Rtt
	}
	return 0
}

func (x *DnsRecord) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *DnsRecord) GetQclass() uint32 {
	if x != nil && x.Qclass != nil {
		return *x.Qclass
	}
	return 0
}

func (x *DnsRecord) GetQclassName() string {
	if x != nil && x.QclassName != nil {
		return *x.QclassName
	}
	return ""
}

func (x *DnsRecord) GetQtype() uint32 {
	if x != nil && x.Qtype != nil {
		return *x.Qtype
	}
	return 0
}

func (x *DnsRecord) GetQtypeName() string {
	if x != nil && x.QtypeName != nil {
		return *x.QtypeName
	}
	return ""
}

func (x *DnsRecord) GetRcode() uint32 {
	if x != nil && x.Rcode != nil {
		return *x.Rcode
	}
	return 0
}

func (x *DnsRecord) GetRcodeName() string {
	if x != nil && x.RcodeName != nil {
		return *x.RcodeName
	}
	return ""
}

func (x *DnsRecord) GetAA() bool {
	if x != nil && x.AA != nil {
		return *x.AA
	}
	return false
}

func (x *DnsRecord) GetTC() bool {
	if x != nil && x.TC != nil {
		return *x.TC
	}
	return false
}

func (x *DnsRecord) GetRD() bool {
	if x != nil && x.RD != nil {
		return *x.RD
	}
	return false
}

func (x *DnsRecord) GetRA() bool {
	if x != nil && x.RA != nil {
		return *x.RA
	}
	return false
}

func (x *DnsRecord) GetZ() uint32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *DnsRecord) GetAnswers() string {
	if x != nil && x.Answers != nil {
		return *x.Answers
	}
	return ""
}

func (x *DnsRecord) GetTTLs() string {
	if x != nil && x.TTLs != nil {
		return *x.TTLs
	}
	return ""
}

func (x *DnsRecord) GetRejected() bool {
	if x != nil && x.Rejected != nil {
		return *x.Rejected
	}
	return false
}

func (x *DnsRecord) GetOpcode() uint32 {
	if x != nil && x.Opcode != nil {
		return *x.Opcode
	}
	return 0
}

func (x *DnsRecord) GetOpcodeName() string {
	if x != nil && x.OpcodeName != nil {
		return *x.OpcodeName
	}
	return ""
}

// Zeek 8 dhcp.log. Unlike the other logs it has no uid or id.* columns: one DHCP exchange can
// span several connections (uids), and the addresses are the DHCP client and server.
type DhcpRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            float64                `protobuf:"fixed64,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Uids          *string                `protobuf:"bytes,2,opt,name=uids,proto3,oneof" json:"uids,omitempty"`
	ClientAddr    *string                `protobuf:"bytes,3,opt,name=client_addr,json=clientAddr,proto3,oneof" json:"client_addr,omitempty"`
	ServerAddr    *string                `protobuf:"bytes,4,opt,name=server_addr,json=serverAddr,proto3,oneof" json:"server_addr,omitempty"`
	ClientPort    *uint32                `protobuf:"varint,5,opt,name=client_port,json=clientPort,proto3,oneof" json:"client_port,omitempty"`
	ServerPort    *uint32                `protobuf:"varint,6,opt,name=server_port,json=serverPort,proto3,oneof" json:"server_port,omitempty"`
	Mac           *string                `protobuf:"bytes,7,opt,name=mac,proto3,oneof" json:"mac,omitempty"`
	HostName      *string                `protobuf:"bytes,8,opt,name=host_name,json=hostName,proto3,oneof" json:"host_name,omitempty"`
	ClientFqdn    *string                `protobuf:"bytes,9,opt,name=client_fqdn,json=clientFqdn,proto3,oneof" json:"client_fqdn,omitempty"`
	Domain        *string                `protobuf:"bytes,10,opt,name=domain,proto3,oneof" json:"domain,omitempty"`
	RequestedAddr *string                `protobuf:"bytes,11,opt,name=requested_addr,json=requestedAddr,proto3,oneof" json:"requested_addr,omitempty"`
	AssignedAddr  *string                `protobuf:"bytes,12,opt,name=assigned_addr,json=assignedAddr,proto3,oneof" json:"assigned_addr,omitempty"`
	LeaseTime     *float64               `protobuf:"fixed64,13,opt,name=lease_time,json=leaseTime,proto3,oneof" json:"lease_time,omitempty"`
	ClientMessage *string                `protobuf:"bytes,14,opt,name=client_message,json=clientMessage,proto3,oneof" json:"client_message,omitempty"`
	ServerMessage *string                `protobuf:"bytes,15,opt,name=server_message,json=serverMessage,proto3,oneof" json:"server_message,omitempty"`
	MsgTypes      *string                `protobuf:"bytes,16,opt,name=msg_types,json=msgTypes,proto3,oneof" json:"msg_types,omitempty"`
	Duration      *float64               `protobuf:"fixed64,17,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	// From Zeek's DHCP software and sub-option policy scripts, when loaded.
	ClientSoftware *string `protobuf:"bytes,18,opt,name=client_software,json=clientSoftware,proto3,oneof" json:"client_software,omitempty"`
	ServerSoftware *string `protobuf:"bytes,19,opt,name=server_software,json=serverSoftware,proto3,oneof" json:"server_software,omitempty"`
	CircuitId      *string `protobuf:"bytes,20,opt,name=circuit_id,json=circuitId,proto3,oneof" json:"circuit_id,omitempty"`
	AgentRemoteId  *string `protobuf:"bytes,21,opt,name=agent_remote_id,json=agentRemoteId,proto3,oneof" json:"agent_remote_id,omitempty"`
	SubscriberId   *string `protobuf:"bytes,22,opt,name=subscriber_id,json=subscriberId,proto3,oneof" json:"subscriber_id,omitempty"`
	// DHCP option 55 as comma-separated decimal bytes, filled in by the sensor from the PCAP.
	ParamReqList  *string `protobuf:"bytes,23,opt,name=param_req_list,json=paramReqList,proto3,oneof" json:"param_req_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DhcpRecord) Reset() {
	*x = DhcpRecord{}
	mi := &file_sensor_records_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DhcpRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DhcpRecord) ProtoMessage() {}

func (x *DhcpRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DhcpRecord.ProtoReflect.Descriptor instead.
func (*DhcpRecord) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{6}
}

func (x *DhcpRecord) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *DhcpRecord) GetUids() string {
	if x != nil && x.Uids != nil {
		return *x.Uids
	}
	return ""
}

func (x *DhcpRecord) GetClientAddr() string {
	if x != nil && x.ClientAddr != nil {
		return *x.ClientAddr
	}
	return ""
}

func (x *DhcpRecord) GetServerAddr() string {
	if x != nil && x.ServerAddr != nil {
		return *x.ServerAddr
	}
	return ""
}

func (x *DhcpRecord) GetClientPort() uint32 {
	if x != nil && x.ClientPort != nil {
		return *x.ClientPort
	}
	return 0
}

func (x *DhcpRecord) GetServerPort() uint32 {
	if x != nil && x.ServerPort != nil {
		return *x.ServerPort
	}
	return 0
}

func (x *DhcpRecord) GetMac() string {
	if x != nil && x.Mac != nil {
		return *x.Mac
	}
	return ""
}

func (x *DhcpRecord) GetHostName() string {
	if x != nil && x.HostName != nil {
		return *x.HostName
	}
	return ""
}

func (x *DhcpRecord) GetClientFqdn() string {
	if x != nil && x.ClientFqdn != nil {
		return *x.ClientFqdn
	}
	return ""
}

func (x *DhcpRecord) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *DhcpRecord) GetRequestedAddr() string {
	if x != nil && x.RequestedAddr != nil {
		return *x.RequestedAddr
	}
	return ""
}

func (x *DhcpRecord) GetAssignedAddr() string {
	if x != nil && x.AssignedAddr != nil {
		return *x.AssignedAddr
	}
	return ""
}

func (x *DhcpRecord) GetLeaseTime() float64 {
	if x != nil && x.LeaseTime != nil {
		return *x.LeaseTime
	}
	return 0
}

func (x *DhcpRecord) GetClientMessage() string {
	if x != nil && x.ClientMessage != nil {
		return *x.ClientMessage
	}
	return ""
}

func (x *DhcpRecord) GetServerMessage() string {
	if x != nil && x.ServerMessage != nil {
		return *x.ServerMessage
	}
	return ""
}

func (x *DhcpRecord) GetMsgTypes() string {
	if x != nil && x.MsgTypes != nil {
		return *x.MsgTypes
	}
	return ""
}

func (x *DhcpRecord) GetDuration() float64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *DhcpRecord) GetClientSoftware() string {
	if x != nil && x.ClientSoftware != nil {
		return *x.ClientSoftware
	}
	return ""
}

func (x *DhcpRecord) GetServerSoftware() string {
	if x != nil && x.ServerSoftware != nil {
		return *x.ServerSoftware
	}
	return ""
}

func (x *DhcpRecord) GetCircuitId() string {
	if x != nil && x.CircuitId != nil {
		return *x.CircuitId
	}
	return ""
}

func (x *DhcpRecord) GetAgentRemoteId() string {
	if x != nil && x.AgentRemoteId != nil {
		return *x.AgentRemoteId
	}
	return ""
}

func (x *DhcpRecord) GetSubscriberId() string {
	if x != nil && x.SubscriberId != nil {
		return *x.SubscriberId
	}
	return ""
}

func (x *DhcpRecord) GetParamReqList() string {
	if x != nil && x.ParamReqList != nil {
		return *x.ParamReqList
	}
	return ""
}

type Ja3Ja4Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            float64                `protobuf:"fixed64,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	OrigH         string                 `protobuf:"bytes,3,opt,name=orig_h,json=origH,proto3" json:"orig_h,omitempty"`
	OrigP         uint32                 `protobuf:"varint,4,opt,name=orig_p,json=origP,proto3" json:"orig_p,omitempty"`
	RespH         string                 `protobuf:"bytes,5,opt,name=resp_h,json=respH,proto3" json:"resp_h,omitempty"`
	RespP         uint32                 `protobuf:"varint,6,opt,name=resp_p,json=respP,proto3" json:"resp_p,omitempty"`
	Ja3           *string                `protobuf:"bytes,7,opt,name=ja3,proto3,oneof" json:"ja3,omitempty"`
	Ja3Hash       *string                `protobuf:"bytes,8,opt,name=ja3_hash,json=ja3Hash,proto3,oneof" json:"ja3_hash,omitempty"`
	Ja4           *string                `protobuf:"bytes,9,opt,name=ja4,proto3,oneof" json:"ja4,omitempty"`
	Ja4Hash       *string                `protobuf:"bytes,10,opt,name=ja4_hash,json=ja4Hash,proto3,oneof" json:"ja4_hash,omitempty"`
	ClientVersion *string                `protobuf:"bytes,11,opt,name=client_version,json=clientVersion,proto3,oneof" json:"client_version,omitempty"`
	CipherSuites  *string                `protobuf:"bytes,12,opt,name=cipher_suites,json=cipherSuites,proto3,oneof" json:"cipher_suites,omitempty"`
	Extensions    *string                `protobuf:"bytes,13,opt,name=extensions,proto3,oneof" json:"extensions,omitempty"`
	ServerName    *string                `protobuf:"bytes,14,opt,name=server_name,json=serverName,proto3,oneof" json:"server_name,omitempty"`
	UserAgent     *string                `protobuf:"bytes,15,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ja3Ja4Record) Reset() {
	*x = Ja3Ja4Record{}
	mi := &file_sensor_records_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ja3Ja4Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ja3Ja4Record) ProtoMessage() {}

func (x *Ja3Ja4Record) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ja3Ja4Record.ProtoReflect.Descriptor instead.
func (*Ja3Ja4Record) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{7}
}

func (x *Ja3Ja4Record) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Ja3Ja4Record) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Ja3Ja4Record) GetOrigH() string {
	if x != nil {
		return x.OrigH
	}
	return ""
}

func (x *Ja3Ja4Record) GetOrigP() uint32 {
	if x != nil {
		return x.OrigP
	}
	return 0
}

func (x *Ja3Ja4Record) GetRespH() string {
	if x != nil {
		return x.RespH
	}
	return ""
}

func (x *Ja3Ja4Record) GetRespP() uint32 {
	if x != nil {
		return x.RespP
	}
	return 0
}

func (x *Ja3Ja4Record) GetJa3() string {
	if x != nil && x.Ja3 != nil {
		return *x.Ja3
	}
	return ""
}

func (x *Ja3Ja4Record) GetJa3Hash() string {
	if x != nil && x.Ja3Hash != nil {
		return *x.Ja3Hash
	}
	return ""
}

func (x *Ja3Ja4Record) GetJa4() string {
	if x != nil && x.Ja4 != nil {
		return *x.Ja4
	}
	return ""
}

func (x *Ja3Ja4Record) GetJa4Hash() string {
	if x != nil && x.Ja4Hash != nil {
		return *x.Ja4Hash
	}
	return ""
}

func (x *Ja3Ja4Record) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

func (x *Ja3Ja4Record) GetCipherSuites() string {
	if x != nil && x.CipherSuites != nil {
		return *x.CipherSuites
	}
	return ""
}

func (x *Ja3Ja4Record) GetExtensions() string {
	if x != nil && x.Extensions != nil {
		return *x.Extensions
	}
	return ""
}

func (x *Ja3Ja4Record) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

func (x *Ja3Ja4Record) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

// The sensor's ja3-ja4-fingerprinting.zeek sets every JA4S field on every record: server_name
// falls back to "Unknown", and an empty server_extensions vector is written as `(empty)`, the
// empty string here. So no field is optional.
type Ja4SRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ts               float64                `protobuf:"fixed64,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Uid              string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	OrigH            string                 `protobuf:"bytes,3,opt,name=orig_h,json=origH,proto3" json:"orig_h,omitempty"`
	OrigP            uint32                 `protobuf:"varint,4,opt,name=orig_p,json=origP,proto3" json:"orig_p,omitempty"`
	RespH            string                 `protobuf:"bytes,5,opt,name=resp_h,json=respH,proto3" json:"resp_h,omitempty"`
	RespP            uint32                 `protobuf:"varint,6,opt,name=resp_p,json=respP,proto3" json:"resp_p,omitempty"`
	Ja4S             string                 `protobuf:"bytes,7,opt,name=ja4s,proto3" json:"ja4s,omitempty"`
	Ja4SHash         string                 `protobuf:"bytes,8,opt,name=ja4s_hash,json=ja4sHash,proto3" json:"ja4s_hash,omitempty"`
	ServerVersion    string                 `protobuf:"bytes,9,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerCipher     string                 `protobuf:"bytes,10,opt,name=server_cipher,json=serverCipher,proto3" json:"server_cipher,omitempty"`
	ServerExtensions string                 `protobuf:"bytes,11,opt,name=server_extensions,json=serverExtensions,proto3" json:"server_extensions,omitempty"`
	ServerName       string                 `protobuf:"bytes,12,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ja4SRecord) Reset() {
	*x = Ja4SRecord{}
	mi := &file_sensor_records_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ja4SRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ja4SRecord) ProtoMessage() {}

func (x *Ja4SRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_records_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ja4SRecord.ProtoReflect.Descriptor instead.
func (*Ja4SRecord) Descriptor() ([]byte, []int) {
	return file_sensor_records_proto_rawDescGZIP(), []int{8}
}

func (x *Ja4SRecord) GetTs() float64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Ja4SRecord) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Ja4SRecord) GetOrigH() string {
	if x != nil {
		return x.OrigH
	}
	return ""
}

func (x *Ja4SRecord) GetOrigP() uint32 {
	if x != nil {
		return x.OrigP
	}
	return 0
}

func (x *Ja4SRecord) GetRespH() string {
	if x != nil {
		return x.RespH
	}
	return ""
}

func (x *Ja4SRecord) GetRespP() uint32 {
	if x != nil {
		return x.RespP
	}
	return 0
}

func (x *Ja4SRecord) GetJa4S() string {
	if x != nil {
		return x.Ja4S
	}
	return ""
}

func (x *Ja4SRecord) GetJa4SHash() string {
	if x != nil {
		return x.Ja4SHash
	}
	return ""
}

func (x *Ja4SRecord) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Ja4SRecord) GetServerCipher() string {
	if x != nil {
		return x.ServerCipher
	}
	return ""
}

func (x *Ja4SRecord) GetServerExtensions() string {
	if x != nil {
		return x.ServerExtensions
	}
	return ""
}

func (x *Ja4SRecord) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

var File_sensor_records_proto protoreflect.FileDescriptor

const file_sensor_records_proto_rawDesc = "" +
	"\n" +
	"\x14sensor_records.proto\x12\x10enigma.ingest.v1\"\x9c\x03\n" +
	"\x14UploadRecordsRequest\x12\x16\n" +
	"\x06apiKey\x18\x01 \x01(\tR\x06apiKey\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\rR\rschemaVersion\x12$\n" +
	"\rsensorVersion\x18\x03 \x01(\tR\rsensorVersion\x126\n" +
	"\x06counts\x18\x04 \x01(\v2\x1e.enigma.ingest.v1.RecordCountsR\x06counts\x12?\n" +
	"\vcompression\x18\x05 \x01(\x0e2\x1d.enigma.ingest.v1.CompressionR\vcompression\x12P\n" +
	"\bmetadata\x18\x06 \x03(\v24.enigma.ingest.v1.UploadRecordsRequest.MetadataEntryR\bmetadata\x12\x18\n" +
	"\arecords\x18\a \x01(\fR\arecords\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\fRecordCounts\x12\x12\n" +
	"\x04conn\x18\x01 \x01(\rR\x04conn\x12\x10\n" +
	"\x03dns\x18\x02 \x01(\rR\x03dns\x12\x12\n" +
	"\x04dhcp\x18\x03 \x01(\rR\x04dhcp\x12\x16\n" +
	"\x06ja3Ja4\x18\x04 \x01(\rR\x06ja3Ja4\x12\x12\n" +
	"\x04ja4s\x18\x05 \x01(\rR\x04ja4s\"i\n" +
	"\x15UploadRecordsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8a\x02\n" +
	"\vRecordBatch\x120\n" +
	"\x04conn\x18\x01 \x03(\v2\x1c.enigma.ingest.v1.ConnRecordR\x04conn\x12-\n" +
	"\x03dns\x18\x02 \x03(\v2\x1b.enigma.ingest.v1.DnsRecordR\x03dns\x120\n" +
	"\x04dhcp\x18\x03 \x03(\v2\x1c.enigma.ingest.v1.DhcpRecordR\x04dhcp\x126\n" +
	"\x06ja3Ja4\x18\x04 \x03(\v2\x1e.enigma.ingest.v1.Ja3Ja4RecordR\x06ja3Ja4\x120\n" +
	"\x04ja4s\x18\x05 \x03(\v2\x1c.enigma.ingest.v1.Ja4sRecordR\x04ja4s\"\x9e\a\n" +
	"\n" +
	"ConnRecord\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x01R\x02ts\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x15\n" +
	"\x06orig_h\x18\x03 \x01(\tR\x05origH\x12\x15\n" +
	"\x06orig_p\x18\x04 \x01(\rR\x05origP\x12\x15\n" +
	"\x06resp_h\x18\x05 \x01(\tR\x05respH\x12\x15\n" +
	"\x06resp_p\x18\x06 \x01(\rR\x05respP\x12\x14\n" +
	"\x05proto\x18\a \x01(\tR\x05proto\x12\x1d\n" +
	"\aservice\x18\b \x01(\tH\x00R\aservice\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\t \x01(\x01H\x01R\bduration\x88\x01\x01\x12\"\n" +
	"\n" +
	"orig_bytes\x18\n" +
	" \x01(\x04H\x02R\torigBytes\x88\x01\x01\x12\"\n" +
	"\n" +
	"resp_bytes\x18\v \x01(\x04H\x03R\trespBytes\x88\x01\x01\x12\"\n" +
	"\n" +
	"conn_state\x18\f \x01(\tH\x04R\tconnState\x88\x01\x01\x12\"\n" +
	"\n" +
	"local_orig\x18\r \x01(\bH\x05R\tlocalOrig\x88\x01\x01\x12\"\n" +
	"\n" +
	"local_resp\x18\x0e \x01(\bH\x06R\tlocalResp\x88\x01\x01\x12&\n" +
	"\fmissed_bytes\x18\x0f \x01(\x04H\aR\vmissedBytes\x88\x01\x01\x12\x1d\n" +
	"\ahistory\x18\x10 \x01(\tH\bR\ahistory\x88\x01\x01\x12 \n" +
	"\torig_pkts\x18\x11 \x01(\x04H\tR\borigPkts\x88\x01\x01\x12'\n" +
	"\rorig_ip_bytes\x18\x12 \x01(\x04H\n" +
	"R\vorigIpBytes\x88\x01\x01\x12 \n" +
	"\tresp_pkts\x18\x13 \x01(\x04H\vR\brespPkts\x88\x01\x01\x12'\n" +
	"\rresp_ip_bytes\x18\x14 \x01(\x04H\fR\vrespIpBytes\x88\x01\x01\x12*\n" +
	"\x0etunnel_parents\x18\x15 \x01(\tH\rR\rtunnelParents\x88\x01\x01\x12\x1e\n" +
	"\bip_proto\x18\x16 \x01(\rH\x0eR\aipProto\x88\x01\x01B\n" +
	"\n" +
	"\b_serviceB\v\n" +
	"\t_durationB\r\n" +
	"\v_orig_bytesB\r\n" +
	"\v_resp_bytesB\r\n" +
	"\v_conn_stateB\r\n" +
	"\v_local_origB\r\n" +
	"\v_local_respB\x0f\n" +
	"\r_missed_bytesB\n" +
	"\n" +
	"\b_historyB\f\n" +
	"\n" +
	"_orig_pktsB\x10\n" +
	"\x0e_orig_ip_bytesB\f\n" +
	"\n" +
	"_resp_pktsB\x10\n" +
	"\x0e_resp_ip_bytesB\x11\n" +
	"\x0f_tunnel_parentsB\v\n" +
	"\t_ip_proto\"\x80\a\n" +
	"\tDnsRecord\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x01R\x02ts\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x15\n" +
	"\x06orig_h\x18\x03 \x01(\tR\x05origH\x12\x15\n" +
	"\x06orig_p\x18\x04 \x01(\rR\x05origP\x12\x15\n" +
	"\x06resp_h\x18\x05 \x01(\tR\x05respH\x12\x15\n" +
	"\x06resp_p\x18\x06 \x01(\rR\x05respP\x12\x14\n" +
	"\x05proto\x18\a \x01(\tR\x05proto\x12\x1e\n" +
	"\btrans_id\x18\b \x01(\rH\x00R\atransId\x88\x01\x01\x12\x15\n" +
	"\x03rtt\x18\t \x01(\x01H\x01R\x03rtt\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\n" +
	" \x01(\tH\x02R\x05query\x88\x01\x01\x12\x1b\n" +
	"\x06qclass\x18\v \x01(\rH\x03R\x06qclass\x88\x01\x01\x12$\n" +
	"\vqclass_name\x18\f \x01(\tH\x04R\n" +
	"qclassName\x88\x01\x01\x12\x19\n" +
	"\x05qtype\x18\r \x01(\rH\x05R\x05qtype\x88\x01\x01\x12\"\n" +
	"\n" +
	"qtype_name\x18\x0e \x01(\tH\x06R\tqtypeName\x88\x01\x01\x12\x19\n" +
	"\x05rcode\x18\x0f \x01(\rH\aR\x05rcode\x88\x01\x01\x12\"\n" +
	"\n" +
	"rcode_name\x18\x10 \x01(\tH\bR\trcodeName\x88\x01\x01\x12\x13\n" +
	"\x02AA\x18\x11 \x01(\bH\tR\x02AA\x88\x01\x01\x12\x13\n" +
	"\x02TC\x18\x12 \x01(\bH\n" +
	"R\x02TC\x88\x01\x01\x12\x13\n" +
	"\x02RD\x18\x13 \x01(\bH\vR\x02RD\x88\x01\x01\x12\x13\n" +
	"\x02RA\x18\x14 \x01(\bH\fR\x02RA\x88\x01\x01\x12\x11\n" +
	"\x01Z\x18\x15 \x01(\rH\rR\x01Z\x88\x01\x01\x12\x1d\n" +
	"\aanswers\x18\x16 \x01(\tH\x0eR\aanswers\x88\x01\x01\x12\x17\n" +
	"\x04TTLs\x18\x17 \x01(\tH\x0fR\x04TTLs\x88\x01\x01\x12\x1f\n" +
	"\brejected\x18\x18 \x01(\bH\x10R\brejected\x88\x01\x01\x12\x1b\n" +
	"\x06opcode\x18\x19 \x01(\rH\x11R\x06opcode\x88\x01\x01\x12$\n" +
	"\vopcode_name\x18\x1a \x01(\tH\x12R\n" +
	"opcodeName\x88\x01\x01B\v\n" +
	"\t_trans_idB\x06\n" +
	"\x04_rttB\b\n" +
	"\x06_queryB\t\n" +
	"\a_qclassB\x0e\n" +
	"\f_qclass_nameB\b\n" +
	"\x06_qtypeB\r\n" +
	"\v_qtype_nameB\b\n" +
	"\x06_rcodeB\r\n" +
	"\v_rcode_nameB\x05\n" +
	"\x03_AAB\x05\n" +
	"\x03_TCB\x05\n" +
	"\x03_RDB\x05\n" +
	"\x03_RAB\x04\n" +
	"\x02_ZB\n" +
	"\n" +
	"\b_answersB\a\n" +
	"\x05_TTLsB\v\n" +
	"\t_rejectedB\t\n" +
	"\a_opcodeB\x0e\n" +
	"\f_opcode_name\"\xbf\t\n" +
	"\n" +
	"DhcpRecord\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x01R\x02ts\x12\x17\n" +
	"\x04uids\x18\x02 \x01(\tH\x00R\x04uids\x88\x01\x01\x12$\n" +
	"\vclient_addr\x18\x03 \x01(\tH\x01R\n" +
	"clientAddr\x88\x01\x01\x12$\n" +
	"\vserver_addr\x18\x04 \x01(\tH\x02R\n" +
	"serverAddr\x88\x01\x01\x12$\n" +
	"\vclient_port\x18\x05 \x01(\rH\x03R\n" +
	"clientPort\x88\x01\x01\x12$\n" +
	"\vserver_port\x18\x06 \x01(\rH\x04R\n" +
	"serverPort\x88\x01\x01\x12\x15\n" +
	"\x03mac\x18\a \x01(\tH\x05R\x03mac\x88\x01\x01\x12 \n" +
	"\thost_name\x18\b \x01(\tH\x06R\bhostName\x88\x01\x01\x12$\n" +
	"\vclient_fqdn\x18\t \x01(\tH\aR\n" +
	"clientFqdn\x88\x01\x01\x12\x1b\n" +
	"\x06domain\x18\n" +
	" \x01(\tH\bR\x06domain\x88\x01\x01\x12*\n" +
	"\x0erequested_addr\x18\v \x01(\tH\tR\rrequestedAddr\x88\x01\x01\x12(\n" +
	"\rassigned_addr\x18\f \x01(\tH\n" +
	"R\fassignedAddr\x88\x01\x01\x12\"\n" +
	"\n" +
	"lease_time\x18\r \x01(\x01H\vR\tleaseTime\x88\x01\x01\x12*\n" +
	"\x0eclient_message\x18\x0e \x01(\tH\fR\rclientMessage\x88\x01\x01\x12*\n" +
	"\x0eserver_message\x18\x0f \x01(\tH\rR\rserverMessage\x88\x01\x01\x12 \n" +
	"\tmsg_types\x18\x10 \x01(\tH\x0eR\bmsgTypes\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\x11 \x01(\x01H\x0fR\bduration\x88\x01\x01\x12,\n" +
	"\x0fclient_software\x18\x12 \x01(\tH\x10R\x0eclientSoftware\x88\x01\x01\x12,\n" +
	"\x0fserver_software\x18\x13 \x01(\tH\x11R\x0eserverSoftware\x88\x01\x01\x12\"\n" +
	"\n" +
	"circuit_id\x18\x14 \x01(\tH\x12R\tcircuitId\x88\x01\x01\x12+\n" +
	"\x0fagent_remote_id\x18\x15 \x01(\tH\x13R\ragentRemoteId\x88\x01\x01\x12(\n" +
	"\rsubscriber_id\x18\x16 \x01(\tH\x14R\fsubscriberId\x88\x01\x01\x12)\n" +
	"\x0eparam_req_list\x18\x17 \x01(\tH\x15R\fparamReqList\x88\x01\x01B\a\n" +
	"\x05_uidsB\x0e\n" +
	"\f_client_addrB\x0e\n" +
	"\f_server_addrB\x0e\n" +
	"\f_client_portB\x0e\n" +
	"\f_server_portB\x06\n" +
	"\x04_macB\f\n" +
	"\n" +
	"_host_nameB\x0e\n" +
	"\f_client_fqdnB\t\n" +
	"\a_domainB\x11\n" +
	"\x0f_requested_addrB\x10\n" +
	"\x0e_assigned_addrB\r\n" +
	"\v_lease_timeB\x11\n" +
	"\x0f_client_messageB\x11\n" +
	"\x0f_server_messageB\f\n" +
	"\n" +
	"_msg_typesB\v\n" +
	"\t_durationB\x12\n" +
	"\x10_client_softwareB\x12\n" +
	"\x10_server_softwareB\r\n" +
	"\v_circuit_idB\x12\n" +
	"\x10_agent_remote_idB\x10\n" +
	"\x0e_subscriber_idB\x11\n" +
	"\x0f_param_req_list\"\xbc\x04\n" +
	"\fJa3Ja4Record\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x01R\x02ts\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x15\n" +
	"\x06orig_h\x18\x03 \x01(\tR\x05origH\x12\x15\n" +
	"\x06orig_p\x18\x04 \x01(\rR\x05origP\x12\x15\n" +
	"\x06resp_h\x18\x05 \x01(\tR\x05respH\x12\x15\n" +
	"\x06resp_p\x18\x06 \x01(\rR\x05respP\x12\x15\n" +
	"\x03ja3\x18\a \x01(\tH\x00R\x03ja3\x88\x01\x01\x12\x1e\n" +
	"\bja3_hash\x18\b \x01(\tH\x01R\aja3Hash\x88\x01\x01\x12\x15\n" +
	"\x03ja4\x18\t \x01(\tH\x02R\x03ja4\x88\x01\x01\x12\x1e\n" +
	"\bja4_hash\x18\n" +
	" \x01(\tH\x03R\aja4Hash\x88\x01\x01\x12*\n" +
	"\x0eclient_version\x18\v \x01(\tH\x04R\rclientVersion\x88\x01\x01\x12(\n" +
	"\rcipher_suites\x18\f \x01(\tH\x05R\fcipherSuites\x88\x01\x01\x12#\n" +
	"\n" +
	"extensions\x18\r \x01(\tH\x06R\n" +
	"extensions\x88\x01\x01\x12$\n" +
	"\vserver_name\x18\x0e \x01(\tH\aR\n" +
	"serverName\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_agent\x18\x0f \x01(\tH\bR\tuserAgent\x88\x01\x01B\x06\n" +
	"\x04_ja3B\v\n" +
	"\t_ja3_hashB\x06\n" +
	"\x04_ja4B\v\n" +
	"\t_ja4_hashB\x11\n" +
	"\x0f_client_versionB\x10\n" +
	"\x0e_cipher_suitesB\r\n" +
	"\v_extensionsB\x0e\n" +
	"\f_server_nameB\r\n" +
	"\v_user_agent\"\xd5\x02\n" +
	"\n" +
	"Ja4sRecord\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x01R\x02ts\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x15\n" +
	"\x06orig_h\x18\x03 \x01(\tR\x05origH\x12\x15\n" +
	"\x06orig_p\x18\x04 \x01(\rR\x05origP\x12\x15\n" +
	"\x06resp_h\x18\x05 \x01(\tR\x05respH\x12\x15\n" +
	"\x06resp_p\x18\x06 \x01(\rR\x05respP\x12\x12\n" +
	"\x04ja4s\x18\a \x01(\tR\x04ja4s\x12\x1b\n" +
	"\tja4s_hash\x18\b \x01(\tR\bja4sHash\x12%\n" +
	"\x0eserver_version\x18\t \x01(\tR\rserverVersion\x12#\n" +
	"\rserver_cipher\x18\n" +
	" \x01(\tR\fserverCipher\x12+\n" +
	"\x11server_extensions\x18\v \x01(\tR\x10serverExtensions\x12\x1f\n" +
	"\vserver_name\x18\f \x01(\tR\n" +
	"serverName*@\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_ZLIB\x10\x012p\n" +
	"\fSensorIngest\x12`\n" +
	"\ruploadRecords\x12&.enigma.ingest.v1.UploadRecordsRequest\x1a'.enigma.ingest.v1.UploadRecordsResponseB1Z/EnigmaNetz/Enigma-Go-Sensor/internal/api/ingestb\x06proto3"

var (
	file_sensor_records_proto_rawDescOnce sync.Once
	file_sensor_records_proto_rawDescData []byte
)

func file_sensor_records_proto_rawDescGZIP() []byte {
	file_sensor_records_proto_rawDescOnce.Do(func() {
		file_sensor_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_records_proto_rawDesc), len(file_sensor_records_proto_rawDesc)))
	})
	return file_sensor_records_proto_rawDescData
}

var file_sensor_records_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sensor_records_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sensor_records_proto_goTypes = []any{
	(Compression)(0),              // 0: enigma.ingest.v1.Compression
	(*UploadRecordsRequest)(nil),  // 1: enigma.ingest.v1.UploadRecordsRequest
	(*RecordCounts)(nil),          // 2: enigma.ingest.v1.RecordCounts
	(*UploadRecordsResponse)(nil), // 3: enigma.ingest.v1.UploadRecordsResponse
	(*RecordBatch)(nil),           // 4: enigma.ingest.v1.RecordBatch
	(*ConnRecord)(nil),            // 5: enigma.ingest.v1.ConnRecord
	(*DnsRecord)(nil),             // 6: enigma.ingest.v1.DnsRecord
	(*DhcpRecord)(nil),            // 7: enigma.ingest.v1.DhcpRecord
	(*Ja3Ja4Record)(nil),          // 8: enigma.ingest.v1.Ja3Ja4Record
	(*Ja4SRecord)(nil),            // 9: enigma.ingest.v1.Ja4sRecord
	nil,                           // 10: enigma.ingest.v1.UploadRecordsRequest.MetadataEntry
}
var file_sensor_records_proto_depIdxs = []int32{
	2,  // 0: enigma.ingest.v1.UploadRecordsRequest.counts:type_name -> enigma.ingest.v1.RecordCounts
	0,  // 1: enigma.ingest.v1.UploadRecordsRequest.compression:type_name -> enigma.ingest.v1.Compression
	10, // 2: enigma.ingest.v1.UploadRecordsRequest.metadata:type_name -> enigma.ingest.v1.UploadRecordsRequest.MetadataEntry
	5,  // 3: enigma.ingest.v1.RecordBatch.conn:type_name -> enigma.ingest.v1.ConnRecord
	6,  // 4: enigma.ingest.v1.RecordBatch.dns:type_name -> enigma.ingest.v1.DnsRecord
	7,  // 5: enigma.ingest.v1.RecordBatch.dhcp:type_name -> enigma.ingest.v1.DhcpRecord
	8,  // 6: enigma.ingest.v1.RecordBatch.ja3Ja4:type_name -> enigma.ingest.v1.Ja3Ja4Record
	9,  // 7: enigma.ingest.v1.RecordBatch.ja4s:type_name -> enigma.ingest.v1.Ja4sRecord
	1,  // 8: enigma.ingest.v1.SensorIngest.uploadRecords:input_type -> enigma.ingest.v1.UploadRecordsRequest
	3,  // 9: enigma.ingest.v1.SensorIngest.uploadRecords:output_type -> enigma.ingest.v1.UploadRecordsResponse
	9,  // [9:10] is the sub-list for method output_type
	8,  // [8:9] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sensor_records_proto_init() }
func file_sensor_records_proto_init() {
	if File_sensor_records_proto != nil {
		return
	}
	file_sensor_records_proto_msgTypes[4].OneofWrappers = []any{}
	file_sensor_records_proto_msgTypes[5].OneofWrappers = []any{}
	file_sensor_records_proto_msgTypes[6].OneofWrappers = []any{}
	file_sensor_records_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_records_proto_rawDesc), len(file_sensor_records_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensor_records_proto_goTypes,
		DependencyIndexes: file_sensor_records_proto_depIdxs,
		EnumInfos:         file_sensor_records_proto_enumTypes,
		MessageInfos:      file_sensor_records_proto_msgTypes,
	}.Build()
	File_sensor_records_proto = out.File
	file_sensor_records_proto_goTypes = nil
	file_sensor_records_proto_depIdxs = nil
}
