// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/api/publish/grpc_config.proto

package publish

import (
	_ "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_publish_grpc_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_publish_grpc_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadExcelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	EmployeeId    string                 `protobuf:"bytes,2,opt,name=employeeId,proto3" json:"employeeId,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadExcelRequest) Reset() {
	*x = UploadExcelRequest{}
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadExcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadExcelRequest) ProtoMessage() {}

func (x *UploadExcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadExcelRequest.ProtoReflect.Descriptor instead.
func (*UploadExcelRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_publish_grpc_config_proto_rawDescGZIP(), []int{2}
}

func (x *UploadExcelRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadExcelRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *UploadExcelRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UploadExcelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadExcelResponse) Reset() {
	*x = UploadExcelResponse{}
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadExcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadExcelResponse) ProtoMessage() {}

func (x *UploadExcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_publish_grpc_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadExcelResponse.ProtoReflect.Descriptor instead.
func (*UploadExcelResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_publish_grpc_config_proto_rawDescGZIP(), []int{3}
}

func (x *UploadExcelResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UploadExcelResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UploadExcelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_api_publish_grpc_config_proto protoreflect.FileDescriptor

const file_internal_api_publish_grpc_config_proto_rawDesc = "" +
	"\n" +
	"&internal/api/publish/grpc_config.proto\x12\apublish\x1a\x19google/protobuf/any.proto\" \n" +
	"\n" +
	"getRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"_\n" +
	"\vgetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcc\x01\n" +
	"\x12uploadExcelRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"employeeId\x18\x02 \x01(\tR\n" +
	"employeeId\x12E\n" +
	"\bmetadata\x18\x03 \x03(\v2).publish.uploadExcelRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x13uploadExcelResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x98\x01\n" +
	"\x0epublishService\x126\n" +
	"\tgetMethod\x12\x13.publish.getRequest\x1a\x14.publish.getResponse\x12N\n" +
	"\x11uploadExcelMethod\x12\x1b.publish.uploadExcelRequest\x1a\x1c.publish.uploadExcelResponseB\x16Z\x14internal/api/publishb\x06proto3"

var (
	file_internal_api_publish_grpc_config_proto_rawDescOnce sync.Once
	file_internal_api_publish_grpc_config_proto_rawDescData []byte
)

func file_internal_api_publish_grpc_config_proto_rawDescGZIP() []byte {
	file_internal_api_publish_grpc_config_proto_rawDescOnce.Do(func() {
		file_internal_api_publish_grpc_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_publish_grpc_config_proto_rawDesc), len(file_internal_api_publish_grpc_config_proto_rawDesc)))
	})
	return file_internal_api_publish_grpc_config_proto_rawDescData
}

var file_internal_api_publish_grpc_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_api_publish_grpc_config_proto_goTypes = []any{
	(*GetRequest)(nil),          // 0: publish.getRequest
	(*GetResponse)(nil),         // 1: publish.getResponse
	(*UploadExcelRequest)(nil),  // 2: publish.uploadExcelRequest
	(*UploadExcelResponse)(nil), // 3: publish.uploadExcelResponse
	nil,                         // 4: publish.uploadExcelRequest.MetadataEntry
}
var file_internal_api_publish_grpc_config_proto_depIdxs = []int32{
	4, // 0: publish.uploadExcelRequest.metadata:type_name -> publish.uploadExcelRequest.MetadataEntry
	0, // 1: publish.publishService.getMethod:input_type -> publish.getRequest
	2, // 2: publish.publishService.uploadExcelMethod:input_type -> publish.uploadExcelRequest
	1, // 3: publish.publishService.getMethod:output_type -> publish.getResponse
	3, // 4: publish.publishService.uploadExcelMethod:output_type -> publish.uploadExcelResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_publish_grpc_config_proto_init() }
func file_internal_api_publish_grpc_config_proto_init() {
	if File_internal_api_publish_grpc_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_publish_grpc_config_proto_rawDesc), len(file_internal_api_publish_grpc_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_publish_grpc_config_proto_goTypes,
		DependencyIndexes: file_internal_api_publish_grpc_config_proto_depIdxs,
		MessageInfos:      file_internal_api_publish_grpc_config_proto_msgTypes,
	}.Build()
	File_internal_api_publish_grpc_config_proto = out.File
	file_internal_api_publish_grpc_config_proto_goTypes = nil
	file_internal_api_publish_grpc_config_proto_depIdxs = nil
}
