name: Build Release Binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-artifacts-reusable.yml
    with:
      artifact_prefix: ${{ github.ref_name }}
      retention_days: 90
      upload_to_release: true
