name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.24.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Remove stray .out file (Windows workaround)
      if: runner.os == 'Windows'
      run: if exist .out del .out
      shell: cmd

    - name: Remove stray .out file (Unix workaround)
      if: runner.os != 'Windows'
      run: rm -f .out

    - name: Run tests
      run: go test -v -race ./...
